# -*- coding: utf-8 -*-
"""Simple Linear Regression Template.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18lkgPBb6CtG5fQnx55LMPRdfEcB_pvDn

# Simple Linear Regression

## Importing Libraries
"""

import numpy as py
import matplotlib.pyplot as plt
import pandas as pd

"""## Importing Data Set"""

data_set =pd.read_csv("/simple linear regression.csv")
X = data_set.iloc[:,:-1]
Y = data_set.iloc[:,-1]
print (X)
print(Y)

"""## Splitting into test and training set"""

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test =train_test_split(X,Y,test_size=0.2,random_state =42)

"""## Training on Training Set using Simple Linear Regression"""

from sklearn.linear_model import LinearRegression
regressor =LinearRegression()
regressor.fit(X_train, Y_train)

"""## Prediction on Test Set"""

y_pred = regressor.predict(X_test)

"""## Visualizing the Training Set"""

plt.scatter(X_train, Y_train, color = 'red')
plt.plot(X_train,regressor.predict(X_train),color ='blue')
plt.title("CTC vs years of experience")
plt.xlabel("years of experience")
plt.ylabel("CTC")

"""## Visualizing the Test Set"""

plt.scatter(X_test, Y_test, color = 'red')
plt.plot(X_train, regressor.predict(X_train), color = 'blue')
plt.title("CTC vs years of experience")
plt.xlabel("Experience in years")
plt.ylabel("CTC")
plt.show()